version: '3.2'
services:
  app:
    container_name: pluginhound-app
    build:
      context: ./
      dockerfile: app.dockerfile
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/var/www/
    networks:
      - app-network
  web:
    container_name: pluginhound-web
    build:
      context: ./
      dockerfile: web.dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/
      - ./.nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 3002:80
    networks:
      - app-network
    depends_on:
      - app
  db:
    container_name: pluginhound-db
    restart: always
    ports:
      - 3008:3306
    build:
      context: ./
      dockerfile: database.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: pluginhound
    tty: true
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
  testdb:
    container_name: pluginhound-test-db
    restart: always
    ports:
      - 3005:3306
    build:
      context: ./
      dockerfile: database.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: pluginhound
    tty: true
    networks:
      - app-network
    volumes:
      - testdb_data:/var/lib/mysql
  workers:
    container_name: pluginhound-workers
    build:
      context: ./
      dockerfile: workers.dockerfile
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/var/www/
      - ./supervisor-confs/:/etc/supervisor/conf.d/
    networks:
      - app-network
  redis:
    container_name: pluginhound-redis
    build:
      context: ./
      dockerfile: redis.dockerfile
    ports:
      - 3004:6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  testdb_data:
