version: '3.2'
services:
  app:
    container_name: waves-saver-app
    build:
      context: ./
      dockerfile: app.dockerfile
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network
  web:
    container_name: waves-saver-web
    build:
      context: ./
      dockerfile: web.dockerfile
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/usr/local/apache2/htdocs/
    ports:
      - 3002:80
    networks:
      - app-network
  db:
    container_name: waves-saver-db
    restart: always
    ports:
      - 3003:3306
    build:
      context: ./
      dockerfile: database.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: waves-saver
    tty: true
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
  testdb:
    container_name: waves-saver-test-db
    restart: always
    ports:
      - 3005:3306
    build:
      context: ./
      dockerfile: database.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: waves-saver
    tty: true
    networks:
      - app-network
    volumes:
      - testdb_data:/var/lib/mysql
  redis:
    container_name: waves-saver-redis
    build:
      context: ./
      dockerfile: redis.dockerfile
    ports:
      - 3004:6379
    networks:
      - app-network
  cypress:
    container_name: waves-saver-cypress
    build:
      context: ./
      dockerfile: cypress.dockerfile
    tty: true
    networks:
      - app-network
    volumes:
      - ./:/home/app
networks:
  app-network:
    driver: bridge
volumes:
  db_data:
  testdb_data:
