version: '3.2'
services:
  pluginhound-app:
    container_name: pluginhound-app
    image: ${DOCKER_REGISTRY}/pluginhound/app:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: app-prod.dockerfile
    environment:
      - TZ=America/New_York
    networks:
      - app-network
  pluginhound-web:
    container_name: pluginhound-web
    image: ${DOCKER_REGISTRY}/pluginhound/web:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: web-prod.dockerfile
    environment:
      - TZ=America/New_York
    ports:
      - 80:80
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
