version: '3.2'
services:
  pluginhound-app:
    container_name: pluginhound-app
    image: ${DOCKER_REGISTRY}/pluginhound/app:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: app-prod.dockerfile
    environment:
      - TZ=America/New_York
    networks:
      - app-network
  pluginhound-web:
    container_name: pluginhound-web
    image: ${DOCKER_REGISTRY}/pluginhound/web:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: web-prod.dockerfile
    restart: unless-stopped
    tty: true
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/var/www/
      - ./.nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - app-network
  pluginhound-workers:
    container_name: pluginhound-workers
    image: ${DOCKER_REGISTRY}/pluginhound/workers:${DOCKER_TAG}
    build:
      context: ./
      dockerfile: workers-prod.dockerfile
    environment:
      - TZ=America/New_York
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
