export const LOAD_PRODUCT_SUCCESS = 'product/LOAD_PRODUCT_SUCCESS';
export const LOAD_PRODUCT_ERROR = 'product/LOAD_PRODUCT_ERROR';
export const LOAD_PRODUCT_HISTORY_SUCCESS = 'product/LOAD_PRODUCT_HISTORY_SUCCESS';
export const LOAD_PRODUCT_HISTORY_ERROR = 'product/LOAD_PRODUCT_HISTORY_ERROR';