export const REGISTER_PROGRESS = 'user/REGISTER_PROGRESS';
export const REGISTER_SUCCESS = 'user/REGISTER_SUCCESS';
export const REGISTER_ERROR = 'user/REGISTER_ERROR';
export const TOGGLE_REGISTER_MODAL = 'user/TOGGLE_REGISTER_MODAL';

export const LOGIN_PROGRESS = 'user/LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'user/LOGIN_ERROR';
export const TOGGLE_LOGIN_MODAL = 'user/TOGGLE_LOGIN_MODAL';
export const LOGOUT = 'user/LOGOUT';

export const UPDATE_SUCCESS = 'user/UPDATE_SUCCESS';
export const UPDATE_ERROR = 'user/UPDATE_ERROR';
export const UPDATE_VERIFYING = 'user/UPDATE_VERIFYING';

export const VERIFY_EMAIL_SUCCESS = 'user/VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_PROGRESS = 'user/VERIFY_EMAIL_PROGRESS';
export const VERIFY_EMAIL_ERROR = 'user/VERIFY_EMAIL_ERROR';

export const UPDATE_USER = 'user/UPDATE_USER';

export const TOGGLE_RESET_MODE = 'user/TOGGLE_RESET_MODE';
export const SEND_RESET_PROGRESS = 'user/SEND_RESET_PROGRESS';
export const SEND_RESET_SUCCESS = 'user/SEND_RESET_SUCCESS';
export const SEND_RESET_ERROR = 'user/SEND_RESET_ERROR';
export const SET_RESET_TOKEN = 'user/SET_RESET_TOKEN';

export const RESET_PASSWORD_PROGRESS = 'user/RESET_PASSWORD_PROGRESS';
export const RESET_PASSWORD_SUCCESS = 'user/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'user/RESET_PASSWORD_ERROR';